@startuml
split
    -[hidden]->
    :High CADD;
    :High REVEL;
split again
    -[hidden]->
    :High Sift;
    :High PolyPhen;
    :Deleterious MutationTaster;
split again
    -[hidden]->
    :Med-High SpliceAI;
end split
:Category Support;
@enduml
