@startuml comparison_decision_tree
(True Positive) -----> (:smile:) : yes
(True Positive) --> (In VCF?) : no
(In VCF?) --> (MOI tests fail?) : yes
(MOI tests fail?) ---> (:smile:) : yes
(MOI tests fail?) --> (AF issues) : no
(AF issues) --> (Bug) : no
(AF issues) --> (:smile:) : yes
(In VCF?) --> (In MT?) : no
(In MT?) --> (Check Pipeline) : no
(In MT?) --> (Variant QC fail) : yes
(Variant QC fail) --> (Review call accuracy) : yes
(Variant QC fail) --> (Category Testing) : no
@enduml
