@startuml variant_filtering
!pragma useVerticalIf on
start
if (Fails Quality Flags) then (yes)
	stop
(no) elseif (Common in Joint-Call) then (yes)
	stop
(no) elseif (Well Normalised) then (yes)
	stop
(no) elseif (Likely AB Ratio) then (yes)
	stop
(no) elseif (Common in  Populations) then (yes)
	stop
(no) elseif (Clinvar Benign) then (yes)
	stop
(no) elseif (In Panel Green Gene) then (no)
	stop
(yes) elseif (No HIGH CSQs) then (yes)
	stop
else (no)
	:Run variant Categorisation;
@enduml
