[categories]
1 = "ClinVar Pathogenic"
3 = "High Impact Variant"
4 = "de Novo"
5 = "High SpliceAI Score"
6 = "AlphaMissense P/LP"
pm5 = "ACMG PM5 - missense in same residue as known pathogenic"
support = "High in Silico Scores"
sv1 = "Predicted LOF SV"
svdb = 'SpliceVarDB Predicted Splice-Altering'
exomiser = 'Variant prioritised by Exomiser'

[GeneratePanelData]
default_panel = 137
obo_file = "gs://cpg-common-test/references/aip/hpo_terms.obo"
panelapp = "https://panelapp.agha.umccr.org/api/v1/panels"
require_pheno_match = [ "FLG", "GJB2", "F2", "F5",]
within_x_months = 3
forbidden_genes = []
forced_panels = [ 144,]

[FindGeneSymbolMap]
chunk_size = 800

[RunHailFiltering]
ac_threshold = 0.01
additional_csq = [ "missense_variant",]
af_semi_rare = 0.01
callset_af_sv_recessive = 0.03
critical_csq = [ "frameshift_variant", "splice_acceptor_variant", "splice_donor_variant", "start_lost", "stop_gained", "stop_lost", "transcript_ablation",]
max_parent_ab = 0.05
minimum_depth = 10
spliceai = 0.5
csq_string = [ "consequence", "symbol", "gene", "feature", "mane_select", "biotype", "exon", "hgvsc", "hgvsp", "cdna_position", "cds_position", "protein_position", "variant_class", "ensp", "lof", "sift", "polyphen", "am_class", "am_pathogenicity",]

[ValidateMOI]
gnomad_dominant = 0.001
gnomad_max_homs_dominant = 0
gnomad_max_homs_recessive = 1
gnomad_max_ac_dominant = 10
gnomad_max_hemi = 1
callset_af_sv_dominant = 0.01
phenotype_match = [ "6",]

[HPOFlagging]
semantic_match = true
min_similarity = 14.0
phenio_db = "gs://cpg-common-test/references/aip/phenotype.db"
gene_to_phenotype = "gs://cpg-common-test/references/aip/genes_to_phenotype.txt"

[RunHailFiltering.cores]
sv = 2
small_variants = 8

[RunHailFiltering.memory]
small_variants = "100Gi"

[RunHailFiltering.storage]
sv = 10

[RunHailFiltering.timeouts]
small_variants = 15000
sv = 3600
