from typing import TYPE_CHECKING

from cpg_utils import Path, config, hail_batch

if TYPE_CHECKING:
    from hailtop.batch.job import BashJob


def make_echtvar_job(
    cohort_id: str,
    sites_only_vcf: str,
    output: Path,
    job_attrs: dict,
) -> 'BashJob':
    """Create a job to annotate gnomAD frequencies using the Echtvar tool."""
    # localise the input VCF
    sites_vcf = hail_batch.get_batch().read_input(sites_only_vcf)

    # this is a single whole-genome file, generated by the echtvar workflow
    gnomad_annotations = hail_batch.get_batch().read_input(config.config_retrieve(['references', 'echtvar_gnomad']))

    job = hail_batch.get_batch().new_job(
        name=f'AnnotateGnomadFrequenciesWithEchtvar: {cohort_id}',
        attributes=job_attrs | {'tool': 'echtvar'},
    )
    job.image(config.config_retrieve(['images', 'echtvar']))
    job.command(f'echtvar anno -e {gnomad_annotations} {sites_vcf} {job.output}')
    job.storage('20Gi').memory('highmem').cpu(4)

    hail_batch.get_batch().write_output(job.output, output)
    return job
